"""add theme columns to restaurant

Revision ID: a6a4a81490e2
Revises: 45a2cfa4c662
Create Date: 2026-04-04 20:17:28.532764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6a4a81490e2'
down_revision: Union[str, Sequence[str], None] = '45a2cfa4c662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('theme_primary', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('theme_accent', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('theme_text', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('theme_card', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'theme_card')
    op.drop_column('restaurants', 'theme_text')
    op.drop_column('restaurants', 'theme_accent')
    op.drop_column('restaurants', 'theme_primary')
    # ### end Alembic commands ###
