"""add banner maps_url to restaurant

Revision ID: ffe587106aba
Revises: a6a4a81490e2
Create Date: 2026-04-17 18:27:17.035056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffe587106aba'
down_revision: Union[str, Sequence[str], None] = 'a6a4a81490e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('banner', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('maps_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'maps_url')
    op.drop_column('restaurants', 'banner')
    # ### end Alembic commands ###
